project:
  type: website
  output-dir: docs
  
filters:
  - iconify

website:
  title: "Cem Özen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: climateforecastory.qmd
        text: Climate Forecastory

format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full
