project:
  type: website
  output-dir: docs
  
filters:
  - iconify

website:
  title: "Cem Özen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: climateforecastory.qmd
        text: Climate Forecastory
  page-footer:
    center: "© 2025 Cem Özen · All rights reserved"

format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full
